In [ ]:
"""
1. Import the numpy package under the name np (★☆☆)
2. Print the numpy version and the configuration (★☆☆)
3. Create a null vector of size 10 (★☆☆)
4. How to find the memory size of any array (★☆☆)
5. How to get the documentation of the numpy add function from the command line? (★☆☆)
6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
7. Create a vector with values ranging from 10 to 49 (★☆☆)
8. Reverse a vector (first element becomes last) (★☆☆
9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
11. Create a 3x3 identity matrix (★☆☆)
12. Create a 3x3x3 array with random values (★☆☆)
13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
14. Create a random vector of size 30 and find the mean value (★☆☆)
15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
16. How to add a border (filled with 0's) around an existing array? (★☆☆)

17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
"""

In [ ]:
"""
1. Importa el paquete numpy con el nombre np (★☆☆)

2. Imprime la versión de numpy y la configuración (★☆☆)

3. Crea un vector nulo de tamaño 10 (★☆☆)

4. ¿Cómo encontrar el tamaño en memoria de cualquier array? (★☆☆)

5. ¿Cómo obtener la documentación de la función add de numpy desde la línea de comandos? (★☆☆)

6. Crea un vector nulo de tamaño 10, pero con el quinto valor igual a 1 (★☆☆)

7. Crea un vector con valores que vayan de 10 a 49 (★☆☆)

8. Invierte un vector (el primer elemento pasa a ser el último) (★☆☆)

9. Crea una matriz 3x3 con valores que vayan de 0 a 8 (★☆☆)

10. Encuentra los índices de los elementos distintos de cero en [1, 2, 0, 0, 4, 0] (★☆☆)

11. Crea una matriz identidad de 3x3 (★☆☆)

12. Crea un array 3x3x3 con valores aleatorios (★☆☆)

13. Crea un array 10x10 con valores aleatorios y encuentra los valores mínimo y máximo (★☆☆)

14. Crea un vector aleatorio de tamaño 30 y encuentra el valor medio (★☆☆)

15. Crea un array 2D con 1 en los bordes y 0 en el interior (★☆☆)

16. ¿Cómo añadir un borde (relleno con ceros) alrededor de un array existente? (★☆☆)

17. ¿Cuál es el resultado de la siguiente expresión? (★☆☆)
0 * np.nan  
np.nan == np.nan  
np.inf > np.nan  
np.nan - np.nan  
np.nan in set([np.nan])  
0.3 == 3 * 0.1  

18. Crea una matriz 5x5 con los valores 1, 2, 3, 4 justo debajo de la diagonal (★☆☆)

19. Crea una matriz 8x8 y rellénala con un patrón de tablero de ajedrez (★☆☆)

20. Considera un array con forma (6, 7, 8), ¿cuál es el índice (x, y, z) del elemento número 100? (★☆☆)


"""

In [1]:
#1. Importa el paquete numpy con el nombre np (★☆☆)
import numpy as np

In [3]:
#2. Imprime la versión de numpy y la configuración (★☆☆)
import numpy as np
#Imprimir versión de numpy
print(np.__version__)
print(np.__config__)

2.4.0
<module 'numpy.__config__' from 'C:\\Users\\Usuario-PC\\anaconda3\\envs\\clase1\\Lib\\site-packages\\numpy\\__config__.py'>


In [4]:
#3. Crea un vector nulo de tamaño 10 (★☆☆)
import numpy as np
array_ex3 = np.zeros(10)
print(array_ex3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#4. ¿Cómo encontrar el tamaño en memoria de cualquier array? (★☆☆)
import numpy as np
array_ex3 = np.zeros(10)
print(array_ex3.nbytes) #nombre_array.nbytes

80


In [9]:
#5. ¿Cómo obtener la documentación de la función add de numpy desde la línea de comandos? (★☆☆)
import numpy as np
help(np.add) #Le quite el valor total porque se ve horrible xd, pero es así

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [11]:
#6. Crea un vector nulo de tamaño 10, pero con el quinto valor igual a 1 (★☆☆)
array_ex6 = np.zeros(10)
array_ex6[9] = 1
print(array_ex6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [12]:
#7. Crea un vector con valores que vayan de 10 a 49 (★☆☆)
array_ex7 = np.arange(10,50)
print(array_ex7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
#8. Invierte un vector (el primer elemento pasa a ser el último) (★☆☆)
array_ex7 = np.arange(10,50)
print(array_ex7)

array_invertido = array_ex7[::-1]
print(array_invertido)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [17]:
#9. Crea una matriz 3x3 con valores que vayan de 0 a 8 (★☆☆)
matriz_ex9 = np.arange(0,9).reshape(3,3)
print(matriz_ex9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
#10. Encuentra los índices de los elementos distintos de cero en [1, 2, 0, 0, 4, 0] (★☆☆)

array_ex10 = np.array([1, 2, 0, 0, 4, 0])
indice = array_ex10 != 0
print(indice)
print("--------------------------------")

mostrar_distintos_0 = array_ex10[indice]
print("indices distintos a 0: ",mostrar_distintos_0)


[ True  True False False  True False]
--------------------------------
indices distintos a 0:  [1 2 4]


In [22]:
#11. Crea una matriz identidad de 3x3 (★☆☆)
matriz_identidad_ex11 = np.eye(3)
print(matriz_identidad_ex11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#12. Crea un array 3x3x3 con valores aleatorios (★☆☆)
#Dice un array de 3D, 3 bloques, 3 filas y 3 columnas
#Si queremos que salga bien, debemos multiplicar las dimensiones y ese será los valores a poner en el array
#Es decir 3 bloques x 3 filas x 3 columnas = 27 elementos
#Si se pone más o se pone menos, el print dará el error
array_3d_ex12 = np.arange(27).reshape(3,3,3)
print(array_3d_ex12)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [44]:
#13. Crea un array 10x10 con valores aleatorios y encuentra los valores mínimo y máximo (★☆☆)

array_ex13 = np.arange(-50,50).reshape(10,10)
array_min = np.min(array_ex13)
array_max = np.max(array_ex13)

print("El mínimo es: ", array_min)
print("El máximo es: ", array_max)


El mínimo es:  -50
El máximo es:  49


In [45]:
#14. Crea un vector aleatorio de tamaño 30 y encuentra el valor medio (★☆☆)
vector_ex14 = np.arange(31)
vector_mid = np.mean(vector_ex14)
print(vector_mid)

15.0


In [50]:
#15. Crea un array 2D con 1 en los bordes y 0 en el interior (★☆☆)
array_ex15 = np.ones((5, 5))
#Desde la fila 1 hasta la penúltima
#Desde la columna 1 hasta la penúltima
array_ex15[1:-1, 1:-1] = 0

print(array_ex15)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [53]:
#16. ¿Cómo añadir un borde (relleno con ceros) alrededor de un array existente? (★☆☆)

array_ex16 = np.zeros((6, 6))

array_ex16[1:-1, 1:-1] = 1

print(array_ex16)


[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [56]:
#17. ¿Cuál es el resultado de la siguiente expresión? (★☆☆)
# 0 * NaN = NaN porque toda operación matemática con NaN siempre será NaN
0 * np.nan 
#Nan es Nan = False, porque NaN no es igual a nada, ni siquiera así mismo
np.nan == np.nan
#False, cualquier operación bool con NaN siempre será False
np.inf > np.nan
# NaN - NaN = NaN porque toda operación matemática con NaN siempre será NaN
np.nan - np.nan  
#Este dará True porque el set reconoce que ya existe, y aunque np.nan != np.nan, ambos tienen el mismo hash
np.nan in set([np.nan])  
0.3 == 3 * 0.1 #Por final esto es falso, los números decimales se representan en binario

#Verificación
#np.isclose(0.3, 3 * 0.1) #se acerca pero no es igual

False

In [66]:
#18. Crea una matriz 5x5 con los valores 1, 2, 3, 4 justo debajo de la diagonal (★☆☆)

#k = 0 → diagonal principal
#k = 1 → una diagonal encima
#k = -1 → una diagonal debajo
matriz_ex18_2 = np.eye(5, k=-1)
matriz_ex18_2[matriz_ex18_2 == 1] = [1,2,3,4]
print(matriz_ex18_2)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
---------------------------------------------
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [71]:
#19. Crea una matriz 8x8 y rellénala con un patrón de tablero de ajedrez (★☆☆)
matriz_ex19 = np.arange(64).reshape(8,8)
matriz_ex19[:2] = 1
matriz_ex19[6:8] = 1
matriz_ex19[2:6] = 0
print(matriz_ex19)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [74]:
#20. Considera un array con forma (6, 7, 8), ¿cuál es el índice (x, y, z) del elemento número 100? (★☆☆)

"""
Usa el row major, (x, y, z) = (6, 7, 8)

Cada fila z tiene: 8 elementos
Cada bloque y tiene: 7 × 8 = 56 elementos
Cada bloque x tiene: 7 × 8 = 56 elementos

Para X debería ser:
x = 100 // (7 × 8) = 100 // 56 = 1
restante = 100 − 56 = 44

Para Y debería ser:
y = 44 // 8 = 5
restante = 44 − 40 = 4


y z sería igual a 4 z=4

entonces: (x, y, z) = (1, 5, 4)
"""
#Creamos el array como nos pude
array_ex20 = np.arange(6 * 7 * 8).reshape(6, 7, 8)

#Unravel index convierte en un índice lineal (100)
#en un índice multidimensional
#usando el orden por defecto (order='C')
indice = np.unravel_index(100, array_ex20.shape)

print(indice)

#Verificamos que sea este:
print(array_ex20[1, 5, 4])

(np.int64(1), np.int64(5), np.int64(4))
100
